export const homeServicesProductsData: any = {
  services: [
    {
      id: '1',
      title: 'Consultoría y Realización Profesionales',
      to: 'services/consultoria-y-realizacion-profesionales',
      description: `Convertimos ideas en proyectos reales con diseño moderno y construcción de calidad.`,
      image: '/assets/images/Services/Consultoria_y_Real/main.webp',
      imageList: [
        { id: '1', image: '/assets/images/Services/Consultoria_y_Real/1.webp' },
        { id: '2', image: '/assets/images/Services/Consultoria_y_Real/2.webp' },
        { id: '3', image: '/assets/images/Services/Consultoria_y_Real/3.png' },
        { id: '4', image: '/assets/images/Services/Consultoria_y_Real/4.webp' },
        { id: '5', image: '/assets/images/Services/Consultoria_y_Real/5.webp' },
        { id: '6', image: '/assets/images/Services/Consultoria_y_Real/6.webp' },
        { id: '6', image: '/assets/images/Services/Consultoria_y_Real/7.jpg' },
      ],
    },
    {
      id: '2',
      title: 'Colocación y Acabados Impecables',
      to: 'services/colocacion-y-acabados-impecables',
      description: `Instalamos y acabamos con precisión, personalizando cada espacio para que sea funcional y atractivo.`,
      image: '/assets/images/Services/Colocacion_y_Acabados_Impecables/main.webp',
      imageList: [
        { id: '1', image: '/assets/images/Services/Colocacion_y_Acabados_Impecables/1.webp' },
        { id: '2', image: '/assets/images/Services/Colocacion_y_Acabados_Impecables/2.webp' },
        { id: '3', image: '/assets/images/Services/Colocacion_y_Acabados_Impecables/3.jpg' },
        { id: '4', image: '/assets/images/Services/Colocacion_y_Acabados_Impecables/4.webp' },
        { id: '5', image: '/assets/images/Services/Colocacion_y_Acabados_Impecables/5.webp' },
        { id: '6', image: '/assets/images/Services/Colocacion_y_Acabados_Impecables/6.webp' },
        { id: '7', image: '/assets/images/Services/Colocacion_y_Acabados_Impecables/7.webp' },
        { id: '8', image: '/assets/images/Services/Colocacion_y_Acabados_Impecables/8.webp' },
      ],
    },
    {
      id: '3',
      title: 'Innovación en Diseño y Funcionalidad',
      to: 'services/innovacion-en-diseno-y-funcionalidad',
      description: `Ofrecemos financiamiento y diseño a medida para que disfrutes de tus espacios ahora y pagues después.`,
      image: '/assets/images/Services/Inovacion/main.webp',
      imageList: [
        { id: '1', image: '/assets/images/Services/Inovacion/1.webp' },
        { id: '2', image: '/assets/images/Services/Inovacion/2.webp' },
        { id: '3', image: '/assets/images/Services/Inovacion/3.webp' },
        { id: '4', image: '/assets/images/Services/Inovacion/4.webp' },
        { id: '5', image: '/assets/images/Services/Inovacion/5.webp' },
        { id: '6', image: '/assets/images/Services/Inovacion/6.webp' },
        { id: '7', image: '/assets/images/Services/Inovacion/7.webp' },
        { id: '8', image: '/assets/images/Services/Inovacion/8.jpg' },
      ],
    },
    {
      id: '4',
      title: 'Tecnología Avanzada en Diseño',
      to: 'services/tecnologia-avanzada-en-diseno',
      description: `Usamos tecnología de punta para crear muebles y espacios personalizados y duraderos.`,
      image: '/assets/images/Services/Tecnología_Avanzada/main.webp',
      imageList: [
        { id: '1', image: '/assets/images/Services/Tecnología_Avanzada/1.webp' },
        { id: '2', image: '/assets/images/Services/Tecnología_Avanzada/2.webp' },
        { id: '3', image: '/assets/images/Services/Tecnología_Avanzada/3.webp' },
        { id: '4', image: '/assets/images/Services/Tecnología_Avanzada/4.webp' },
        { id: '5', image: '/assets/images/Services/Tecnología_Avanzada/5.webp' },
      ],
    },
    {
      id: '5',
      title: 'Planificación y Mantenimiento Expertos',
      to: 'services/planificacion-y-mantenimiento-expertos',
      description: `Planificamos y mantenemos tus espacios cuidadosamente para asegurar su durabilidad y buena condición.`,
      image: '/assets/images/Services/Planificación_Mantenimiento/main.webp',
      imageList: [
        { id: '1', image: '/assets/images/Services/Planificación_Mantenimiento/1.webp' },
        { id: '2', image: '/assets/images/Services/Planificación_Mantenimiento/2.webp' },
        { id: '3', image: '/assets/images/Services/Planificación_Mantenimiento/3.webp' },
        { id: '4', image: '/assets/images/Services/Planificación_Mantenimiento/4.webp' },
        { id: '5', image: '/assets/images/Services/Planificación_Mantenimiento/5.webp' },
        { id: '6', image: '/assets/images/Services/Planificación_Mantenimiento/6.webp' },
      ],
    },
  ],
  products: [
    {
      id: '1',
      title: 'Mobiliario con Superficies Sólidas',
      to: 'products/mobiliario-con-superficies-solidas',
      description: `Fabricamos muebles de madera fina, metal resistente y acrílicos versátiles, cada uno diseñado para estilos desde clásicos hasta vanguardistas.`,
      image: '/assets/images/Products/Superficies_solidas/main.webp',
      imageList: [
        { id: '1', image: '/assets/images/Products/Superficies_solidas/1.webp' },
        { id: '2', image: '/assets/images/Products/Superficies_solidas/2.webp' },
        { id: '3', image: '/assets/images/Products/Superficies_solidas/3.webp' },
        { id: '4', image: '/assets/images/Products/Superficies_solidas/4.webp' },
        { id: '5', image: '/assets/images/Products/Superficies_solidas/5.webp' },
        { id: '6', image: '/assets/images/Products/Superficies_solidas/6.webp' },
        { id: '7', image: '/assets/images/Products/Superficies_solidas/7.webp' },
      ],
    },
    {
      id: '2',
      title: 'Mobiliario PoP (Point of Purchase)',
      to: 'products/mobiliario-pop',
      description: `Diseñamos mobiliario para puntos de venta que mejora la visibilidad y la experiencia de compra con exhibidores y stands atractivos.`,
      image: '/assets/images/Products/POP/main.webp',
      imageList: [
        { id: '1', image: '/assets/images/Products/POP/1.webp' },
        { id: '2', image: '/assets/images/Products/POP/2.webp' },
        { id: '3', image: '/assets/images/Products/POP/3.webp' },
        { id: '4', image: '/assets/images/Products/POP/4.webp' },
        { id: '5', image: '/assets/images/Products/POP/5.webp' },
        { id: '6', image: '/assets/images/Products/POP/6.webp' },
        { id: '7', image: '/assets/images/Products/POP/7.webp' },
      ],
    },
    {
      id: '3',
      title: 'Anuncios Luminosos',
      to: 'products/anuncios-luminosos',
      description: `Creemos anuncios luminosos que aseguran que tu marca se vea bien tanto de día como de noche, perfectos para cualquier ambiente.`,
      image: '/assets/images/Products/Anuncios/anuncios-luminosos-acrilico-002.jpg',
      imageList: [
        { id: '1', image: '/assets/images/Products/Anuncios/1.webp' },
        { id: '2', image: '/assets/images/Products/Anuncios/2.jpeg' },
        { id: '3', image: '/assets/images/Products/Anuncios/3.jpeg' },
        { id: '4', image: '/assets/images/Products/Anuncios/4.jpeg' },
        { id: '5', image: '/assets/images/Products/Anuncios/5.jpg' },
      ],
    },
    {
      id: '4',
      title: 'Señalización',
      to: 'products/senalizacion',
      description: `Proveemos señalización para guiar, informar y reforzar tu marca en entornos comerciales y corporativos, combinando estilo y funcionalidad.`,
      image: '/assets/images/Products/senalizacion/main.webp',
      imageList: [
        { id: '1', image: '/assets/images/Products/senalizacion/1.webp' },
        { id: '2', image: '/assets/images/Products/senalizacion/2.webp' },
        { id: '3', image: '/assets/images/Products/senalizacion/3.webp' },
        { id: '4', image: '/assets/images/Products/senalizacion/4.webp' },
        { id: '5', image: '/assets/images/Products/senalizacion/5.webp' },
        { id: '6', image: '/assets/images/Products/senalizacion/6.webp' },
        { id: '7', image: '/assets/images/Products/senalizacion/7.webp' },
        { id: '8', image: '/assets/images/Products/senalizacion/8.webp' },
        { id: '9', image: '/assets/images/Products/senalizacion/9.webp' },
      ],
    },
    {
      id: '5',
      title: 'Impresión Digital',
      to: 'products/impresion-digital',
      description: `Especialistas en vinilos autoadhesivos para decorar y personalizar espacios con gráficos de alto impacto visual.`,
      image: '/assets/images/Products/impresion/main.webp',
      imageList: [
        { id: '1', image: '/assets/images/Products/impresion/1.webp' },
        { id: '2', image: '/assets/images/Products/impresion/2.webp' },
        { id: '3', image: '/assets/images/Products/impresion/3.webp' },
        { id: '4', image: '/assets/images/Products/impresion/4.webp' },
        { id: '5', image: '/assets/images/Products/impresion/5.webp' },
        { id: '6', image: '/assets/images/Products/impresion/6.webp' },
        { id: '7', image: '/assets/images/Products/impresion/7.webp' },
        { id: '8', image: '/assets/images/Products/impresion/8.webp' },
        { id: '9', image: '/assets/images/Products/impresion/9.webp' },
      ],
    },
    {
      id: '6',
      title: 'Carpintería',
      to: 'products/carpinteria',
      description: `Ofrecemos carpintería personalizada en sitio, asegurando ajuste perfecto y acabados de calidad con un enfoque en los detalles.`,
      image: '/assets/images/Products/carpinteria/main.webp',
      imageList: [
        { id: '1', image: '/assets/images/Products/carpinteria/1.webp' },
        { id: '2', image: '/assets/images/Products/carpinteria/2.webp' },
        { id: '3', image: '/assets/images/Products/carpinteria/3.webp' },
        { id: '4', image: '/assets/images/Products/carpinteria/4.webp' },
        { id: '5', image: '/assets/images/Products/carpinteria/5.webp' },
        { id: '6', image: '/assets/images/Products/carpinteria/6.webp' },
        { id: '7', image: '/assets/images/Products/carpinteria/7.webp' },
        { id: '8', image: '/assets/images/Products/carpinteria/8.webp' },
      ],
    },
    {
      id: '4',
      title: 'Techos, Pisos y Paredes',
      to: 'products/techos-pisos-y-paredes',
      description: `Brindamos soluciones completas para techos, pisos y paredes, con materiales y acabados que combinan estética, funcionalidad y durabilidad.`,
      image: '/assets/images/Products/techos/main.webp',
      imageList: [
        { id: '1', image: '/assets/images/Products/techos/1.webp' },
        { id: '2', image: '/assets/images/Products/techos/2.webp' },
        { id: '3', image: '/assets/images/Products/techos/3.webp' },
        { id: '4', image: '/assets/images/Products/techos/4.webp' },
        { id: '5', image: '/assets/images/Products/techos/5.webp' },
        { id: '6', image: '/assets/images/Products/techos/6.webp' },
      ],
    },
  ],
};
