export const homeServicesProductsData: any = {
  services: [
    {
      id: '1',
      title: 'Consultoría de Imagen y Desarrollo de Producto',
      to: 'services/consultoria-y-realizacion-profesionales',
      miniDescription: `Convertimos ideas en proyectos reales con diseño moderno y construcción de calidad.`,
      description: `Nuestra empresa se dedica al desarrollo de mobiliario innovador, basado en los requerimientos específicos de cada cliente. Diseñamos soluciones personalizadas que combinan funcionalidad, estética y sostenibilidad. Nuestro equipo de diseñadores trabaja en estrecha colaboración con nuestros clientes para crear piezas de mobiliario únicas y adaptadas a sus necesidades para PDV. Utilizamos materiales de alta calidad y técnicas vanguardistas para garantizar durabilidad y estilo innovador. La satisfacción del cliente es nuestra prioridad, ofreciendo productos que superan sus expectativas.`,
      image: '/assets/images/Services/Consultoria_y_Real/main.webp',
      imageList: [
        { id: '1', image: '/assets/images/Services/Consultoria_y_Real/1.webp' },
        { id: '2', image: '/assets/images/Services/Consultoria_y_Real/2.webp' },
        { id: '3', image: '/assets/images/Services/Consultoria_y_Real/3.png' },
        { id: '4', image: '/assets/images/Services/Consultoria_y_Real/4.webp' },
        { id: '5', image: '/assets/images/Services/Consultoria_y_Real/5.webp' },
        { id: '6', image: '/assets/images/Services/Consultoria_y_Real/6.webp' },
        { id: '6', image: '/assets/images/Services/Consultoria_y_Real/7.jpg' },
      ],
    },
    {
      id: '2',
      title: 'Acabados',
      to: 'services/colocacion-y-acabados-impecables',
      miniDescription: `Instalamos y acabamos con precisión, personalizando cada espacio para que sea funcional y atractivo.`,
      description: `Instalamos y acabamos con precisión, personalizando cada espacio para que sea funcional y atractivo.`,
      image: '/assets/images/Services/Colocacion_y_Acabados_Impecables/main.webp',
      imageList: [
        { id: '1', image: '/assets/images/Services/Colocacion_y_Acabados_Impecables/1.webp' },
        { id: '2', image: '/assets/images/Services/Colocacion_y_Acabados_Impecables/2.webp' },
        { id: '3', image: '/assets/images/Services/Colocacion_y_Acabados_Impecables/3.jpg' },
        { id: '4', image: '/assets/images/Services/Colocacion_y_Acabados_Impecables/4.webp' },
        { id: '5', image: '/assets/images/Services/Colocacion_y_Acabados_Impecables/5.webp' },
        { id: '6', image: '/assets/images/Services/Colocacion_y_Acabados_Impecables/6.webp' },
        { id: '7', image: '/assets/images/Services/Colocacion_y_Acabados_Impecables/7.webp' },
        { id: '8', image: '/assets/images/Services/Colocacion_y_Acabados_Impecables/8.webp' },
      ],
    },
    {
      id: '3',
      title: 'Diseño e interiorism',
      to: 'services/innovacion-en-diseno-y-funcionalidad',
      miniDescription:
        'Ofrecemos soluciones en mobiliario innovador para decorar tus espacios con los mejores diseños',
      description: `Nuestra empresa se especializa en el diseño, fabricación y venta de soluciones de interiorismo. Creamos espacios únicos y funcionales, adaptados a las necesidades y gustos de cada cliente. Nuestro equipo de diseñadores y artesanos trabaja en conjunto para ofrecer mobiliario y decoraciones de alta calidad. Utilizamos materiales de primera y técnicas innovadoras para garantizar resultados excepcionales. La satisfacción del cliente es nuestra prioridad, brindando productos que transforman cualquier espacio en un lugar extraordinario.`,
      image: '/assets/images/Services/Inovacion/main.webp',
      imageList: [
        { id: '1', image: '/assets/images/Services/Inovacion/1.webp' },
        { id: '2', image: '/assets/images/Services/Inovacion/2.webp' },
        { id: '3', image: '/assets/images/Services/Inovacion/3.webp' },
        { id: '4', image: '/assets/images/Services/Inovacion/4.webp' },
        { id: '5', image: '/assets/images/Services/Inovacion/5.webp' },
        { id: '6', image: '/assets/images/Services/Inovacion/6.webp' },
        { id: '7', image: '/assets/images/Services/Inovacion/7.webp' },
        { id: '8', image: '/assets/images/Services/Inovacion/8.jpeg' },
      ],
    },
    {
      id: '4',
      title: 'Tecnología al Servicio de Nuestros Clientes',
      to: 'services/tecnologia-avanzada-en-diseno',
      miniDescription: `Usamos tecnología de punta para crear muebles y espacios personalizados y duraderos.`,
      description: `En MUDEBU nos orgullecemos de utilizar tecnología de punta en todos nuestros procesos de producción. Empleamos maquinaria avanzada y sistemas automatizados para garantizar precisión y eficiencia en cada etapa. Innovamos constantemente para incorporar las últimas tecnologías, asegurando productos de la más alta calidad. Nuestro compromiso con la modernización nos permite ofrecer soluciones personalizadas y adaptadas a las necesidades de nuestros clientes. La excelencia y la innovación tecnológica son la base de nuestra operación, destacándonos en el mercado.`,
      image: '/assets/images/Services/Tecnología_Avanzada/main.webp',
      imageList: [
        { id: '1', image: '/assets/images/Services/Tecnología_Avanzada/1.webp' },
        { id: '2', image: '/assets/images/Services/Tecnología_Avanzada/2.webp' },
        { id: '3', image: '/assets/images/Services/Tecnología_Avanzada/3.webp' },
        { id: '4', image: '/assets/images/Services/Tecnología_Avanzada/4.webp' },
        { id: '5', image: '/assets/images/Services/Tecnología_Avanzada/5.webp' },
      ],
    },
    {
      id: '5',
      title: 'Expertos en Mantenimiento Correctivo y Preventivo',
      to: 'services/planificacion-y-mantenimiento-expertos',
      miniDescription: `Planificamos y mantenemos tus espacios cuidadosamente para asegurar su durabilidad y buena condición.`,
      description: `Nuestra empresa se especializa en el diseño, fabricación y venta de soluciones de interiorismo. Creamos espacios únicos y funcionales, adaptados a las necesidades y gustos de cada cliente. Nuestro equipo de diseñadores y artesanos trabaja en conjunto para ofrecer mobiliario y decoraciones de alta calidad. Utilizamos materiales de primera y técnicas innovadoras para garantizar resultados excepcionales. La satisfacción del cliente es nuestra prioridad, brindando productos que transforman cualquier espacio en un lugar extraordinario.`,
      image: '/assets/images/Services/Planificación_Mantenimiento/main.webp',
      imageList: [
        { id: '1', image: '/assets/images/Services/Planificación_Mantenimiento/1.webp' },
        { id: '2', image: '/assets/images/Services/Planificación_Mantenimiento/2.webp' },
        { id: '3', image: '/assets/images/Services/Planificación_Mantenimiento/3.webp' },
        { id: '4', image: '/assets/images/Services/Planificación_Mantenimiento/4.webp' },
        { id: '5', image: '/assets/images/Services/Planificación_Mantenimiento/5.webp' },
        { id: '6', image: '/assets/images/Services/Planificación_Mantenimiento/6.webp' },
      ],
    },
  ],
  products: [
    // {
    //   id: '1',
    //   title: 'Mobiliario con Superficies Sólidas',
    //   to: 'products/mobiliario-con-superficies-solidas',
    //   description: `Fabricamos muebles de madera fina, metal resistente y acrílicos versátiles, cada uno diseñado para estilos desde clásicos hasta vanguardistas.`,
    //   image: '/assets/images/Products/Superficies_solidas/main.webp',
    //   imageList: [
    //     { id: '1', image: '/assets/images/Products/Superficies_solidas/1.webp' },
    //     { id: '2', image: '/assets/images/Products/Superficies_solidas/2.webp' },
    //     { id: '3', image: '/assets/images/Products/Superficies_solidas/3.webp' },
    //     { id: '4', image: '/assets/images/Products/Superficies_solidas/4.webp' },
    //     { id: '5', image: '/assets/images/Products/Superficies_solidas/5.webp' },
    //     { id: '6', image: '/assets/images/Products/Superficies_solidas/6.webp' },
    //     { id: '7', image: '/assets/images/Products/Superficies_solidas/7.webp' },
    //   ],
    // },
    {
      id: '2',
      title: 'Mobiliario POP (Point of Purchase)',
      to: 'products/mobiliario-pop',
      miniDescription:
        'Diseñamos y fabricamos mobiliario para el punto de venta en madera, metal, acrílico y superficies sólidas',
      description: `Nuestra empresa se especializa en la fabricación de mobiliario para puntos de venta, combinando diseño y funcionalidad para crear espacios comerciales atractivos y eficientes. Utilizamos materiales de alta calidad y tecnología de punta para garantizar durabilidad y estética en cada pieza. Nuestro equipo de expertos trabaja en colaboración con los clientes para desarrollar soluciones personalizadas que optimizan la presentación de productos y mejoran la experiencia del cliente. Nos comprometemos a entregar mobiliario innovador que refuerza la identidad de marca y maximiza el impacto visual. La satisfacción del cliente es nuestra prioridad, ofreciendo productos que superan expectativas.`,
      image: '/assets/images/Products/POP/main.webp',
      imageList: [
        { id: '1', image: '/assets/images/Products/POP/1.webp' },
        { id: '2', image: '/assets/images/Products/POP/2.webp' },
        { id: '3', image: '/assets/images/Products/POP/3.webp' },
        { id: '4', image: '/assets/images/Products/POP/4.webp' },
        { id: '5', image: '/assets/images/Products/POP/5.webp' },
        { id: '6', image: '/assets/images/Products/POP/6.webp' },
        { id: '7', image: '/assets/images/Products/POP/7.webp' },
      ],
    },
    {
      id: '3',
      title: 'Anuncios Luminosos y Señalización',
      to: 'products/anuncios-luminosos',
      miniDescription: `Creemos anuncios luminosos que aseguran que tu marca se vea bien tanto de día como de noche, perfectos para cualquier ambiente.`,
      description:
        'Nuestra empresa se dedica a la fabricación y colocación de anuncios luminosos y señalización, combinando tecnología avanzada y materiales de alta calidad. Creamos soluciones personalizadas para resaltar la identidad de marca de nuestros clientes y garantizar máxima visibilidad. Nuestro equipo de profesionales se encarga de todo el proceso, desde el diseño hasta la instalación final. Nos esforzamos por ofrecer productos duraderos y atractivos que superen las expectativas. La satisfacción del cliente es nuestra prioridad, asegurando un servicio impecable en cada proyecto.',
      image: '/assets/images/Products/Anuncios/anuncios-luminosos-acrilico-002.jpg',
      imageList: [
        { id: '1', image: '/assets/images/Products/Anuncios/1.webp' },
        { id: '2', image: '/assets/images/Products/Anuncios/2.jpeg' },
        { id: '3', image: '/assets/images/Products/Anuncios/3.jpeg' },
        { id: '4', image: '/assets/images/Products/Anuncios/4.jpeg' },
        { id: '5', image: '/assets/images/Products/Anuncios/5.jpg' },
      ],
    },
    // {
    //   id: '4',
    //   title: 'Señalización',
    //   to: 'products/senalizacion',
    //   description: `Proveemos señalización para guiar, informar y reforzar tu marca en entornos comerciales y corporativos, combinando estilo y funcionalidad.`,
    //   image: '/assets/images/Products/senalizacion/main.webp',
    //   imageList: [
    //     { id: '1', image: '/assets/images/Products/senalizacion/1.webp' },
    //     { id: '2', image: '/assets/images/Products/senalizacion/2.webp' },
    //     { id: '3', image: '/assets/images/Products/senalizacion/3.webp' },
    //     { id: '4', image: '/assets/images/Products/senalizacion/4.webp' },
    //     { id: '5', image: '/assets/images/Products/senalizacion/5.webp' },
    //     { id: '6', image: '/assets/images/Products/senalizacion/6.webp' },
    //     { id: '7', image: '/assets/images/Products/senalizacion/7.webp' },
    //     { id: '8', image: '/assets/images/Products/senalizacion/8.webp' },
    //     { id: '9', image: '/assets/images/Products/senalizacion/9.webp' },
    //   ],
    // },
    {
      id: '5',
      title: 'Impresión Digital',
      to: 'products/impresion-digital',
      miniDescription: `Especialistas en vinilos autoadhesivos para decorar y personalizar espacios con gráficos de alto impacto visual.`,
      description: `Nuestra empresa se especializa en impresión digital de gran formato, empleando plotters UV y tecnología de corte de última generación. Creamos soluciones personalizadas para diversas aplicaciones, asegurando calidad y precisión en cada trabajo. Ofrecemos desde gráficos impactantes hasta señalización y displays promocionales. Nuestro equipo de expertos garantiza resultados excepcionales y entregas puntuales. La satisfacción del cliente es nuestra prioridad, entregando productos que sobresalen y cumplen con los más altos estándares de calidad.`,
      image: '/assets/images/Products/impresion/main.webp',
      imageList: [
        { id: '1', image: '/assets/images/Products/impresion/1.webp' },
        { id: '2', image: '/assets/images/Products/impresion/2.webp' },
        { id: '3', image: '/assets/images/Products/impresion/3.webp' },
        { id: '4', image: '/assets/images/Products/impresion/4.webp' },
        { id: '5', image: '/assets/images/Products/impresion/5.webp' },
        { id: '6', image: '/assets/images/Products/impresion/6.webp' },
        { id: '7', image: '/assets/images/Products/impresion/7.webp' },
        { id: '8', image: '/assets/images/Products/impresion/8.webp' },
        { id: '9', image: '/assets/images/Products/impresion/9.webp' },
      ],
    },
    // {
    //   id: '6',
    //   title: 'Carpintería',
    //   to: 'products/carpinteria',
    //   description: `Ofrecemos carpintería personalizada en sitio, asegurando ajuste perfecto y acabados de calidad con un enfoque en los detalles.`,
    //   image: '/assets/images/Products/carpinteria/main.webp',
    //   imageList: [
    //     { id: '1', image: '/assets/images/Products/carpinteria/1.webp' },
    //     { id: '2', image: '/assets/images/Products/carpinteria/2.webp' },
    //     { id: '3', image: '/assets/images/Products/carpinteria/3.webp' },
    //     { id: '4', image: '/assets/images/Products/carpinteria/4.webp' },
    //     { id: '5', image: '/assets/images/Products/carpinteria/5.webp' },
    //     { id: '6', image: '/assets/images/Products/carpinteria/6.webp' },
    //     { id: '7', image: '/assets/images/Products/carpinteria/7.webp' },
    //     { id: '8', image: '/assets/images/Products/carpinteria/8.webp' },
    //   ],
    // },
    {
      id: '4',
      title: 'Obra Civil y Adecuación de Locales Comerciales',
      to: 'products/techos-pisos-y-paredes',
      miniDescription: `Brindamos soluciones completas para techos, pisos y paredes, con materiales y acabados que combinan estética, funcionalidad y durabilidad.`,
      description:
        'Nuestra empresa se dedica a la construcción y adecuación de locales comerciales, creando espacios funcionales y atractivos. Ofrecemos soluciones integrales que abarcan desde el diseño inicial hasta la entrega final del proyecto. Utilizamos materiales de alta calidad y técnicas innovadoras para garantizar durabilidad y estética. Nuestro equipo de profesionales trabaja en estrecha colaboración con los clientes para cumplir con sus necesidades y expectativas. La satisfacción del cliente es nuestra prioridad, asegurando resultados excepcionales en cada proyecto.',
      image: '/assets/images/Products/techos/main.webp',
      imageList: [
        { id: '1', image: '/assets/images/Products/techos/1.webp' },
        { id: '2', image: '/assets/images/Products/techos/2.webp' },
        { id: '3', image: '/assets/images/Products/techos/3.webp' },
        { id: '4', image: '/assets/images/Products/techos/4.webp' },
        { id: '5', image: '/assets/images/Products/techos/5.webp' },
        { id: '6', image: '/assets/images/Products/techos/6.webp' },
      ],
    },
  ],
};
